name: PHP PHPUnit Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master  

jobs:
  phpunit:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run PHPUnit in Docker
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:/var/www/html \
          -w /var/www/html \
          php:8.3-cli \
          bash -c "
            # Installer Composer
            curl -sS https://getcomposer.org/installer | php;
            mv composer.phar /usr/local/bin/composer;

            # Installer les dépendances avec Composer
            composer install --prefer-dist --no-interaction;

            # Exécuter les tests PHPUnit
            ./vendor/bin/phpunit"
