name: PHP PHPUnit Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master  

jobs:
  phpunit:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker://php:8.3-cli

    - name: Run PHPUnit in Docker
      run: |
        docker run --rm \
          -v $GITHUB_WORKSPACE:/var/www/html \
          -w /var/www/html \
          php:8.3-cli \
          bash -c "composer install && ./vendor/bin/phpunit"
